#define BMS_LV_ID 0xFF

#define BMS_HV_ID 0xAA
#define VOLTAGE_FB 0x01 
#define TEMPERATURE_FB 0x0A
#define CURRENT_FB 0x05
#define ERRORS_FB 0x08
#define WARNINGS_FB 0x09

#define PEDALS_ID 0xB0
#define THROTTLE_FB 0x01 
#define BRAKE_FB 0x02

#define IMU_SWE_ID 0xC0
#define IMU_GYRO_FB 0x01 
#define IMU_ACCEL_FB 0x00
#define SWE_FB 0x02

#define GPS_FWE_ID 0xD0
#define LATSPD_FB 0x10 
#define LONALT_FB 0x11
#define TIME_FB 0x12 
#define TTM_FB 0x13
#define FRONT_WHEELS_RIGHT_FB 0x06
#define FRONT_WHEELS_LEFT_FB 0x07
#define DISTANCE_FB 0x08 

#define WHEEL_ID 0xA0
#define GEARS_FB 0x01
#define MARKER_FB 0x64
#define SIGNAL_FB 0x65

#define CURRENT_FB 0x05
#define ERRORS_FB 0x08
#define WARNINGS_FB 0x09

#define VOLTAGE_FB 0x01 
#define TEMPERATURE_FB 0x0A
#define CURRENT_FB 0x05
#define ERRORS_FB 0x08
#define WARNINGS_FB 0x09

#define VOLTAGE_FB 0x01 
#define TEMPERATURE_FB 0x0A
#define CURRENT_FB 0x05
#define ERRORS_FB 0x08
#define WARNINGS_FB 0x09

#define INVERTER_RIGHT_ID 0x181
#define INVERTER_RIGHT_SPEED_FB 0xA8
#define INVERTER_RIGHT_TEMPERATURE_IGBT_FB 0x4A
#define INVERTER_RIGHT_TEMPERATURE_MOTORS_FB 0x49

#define INVERTER_LEFT_ID 0x182
#define INVERTER_LEFT_SPEED_FB 0xA8
#define INVERTER_LEFT_TEMPERATURE_IGBT_FB 0x4A
#define INVERTER_LEFT_TEMPERATURE_MOTORS_FB 0x49